name: ui_tap
description: "ui tap"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  path_provider: ^2.1.1
  geocoding: ^3.0.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  intl: ^0.20.2
  go_router: ^14.1.0
  url_launcher: ^6.2.2
  table_calendar: ^3.1.1
  flutter_localizations:
    sdk: flutter
  # UI & Fonts

  google_fonts: ^6.2.1
  flutter_svg: ^2.2.1
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.2
  cached_network_image: ^3.3.1

  # State Management
  provider: ^6.1.2

  # Network
  dio: ^5.4.2

  # Localization & Storage
  shared_preferences: ^2.3.2

  # Media
  image_picker: ^1.1.2

  # Notifications
  flutter_local_notifications: ^17.2.2


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app-icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/